### PR TITLE
✨ TWEAK: WPCS + I18N

### PR DESCRIPTION
**Pull request by omnisite**
- applied WordPress Coding Standards (https://developer.wordpress.org/coding-standards/wordpress-coding-standards/)
- made strings translatable + added pot file

### CODE REVIEW

**Comment by warengonzaga** [comment]
Hye @omnisite thanks for the amazing update, can you share details about using the translation file? For example, I want to translate it into Tagalog?

**Review by warengonzaga — COMMENTED** [review]
All good to my end just wanna understand the translation file. Happy to merge once provided details about it. Moving forward if we wanna add more translation to it.

**Comment by omnisite** [comment]
Sure: in /languages you can put your language files. I added a .pot file. This can be opened in POEdit and then you make a language you want and edit the strings in POEdit. Then you get a .mo and .po file and those you put in /languages. The filename should be "update-your-footer-wp-nl_NL.po (and .mo), where you replace nl_NL with the Tagalog codes (I think that is "tl" -> https://theme-fusion.com/documentation/avada/translations/complete-list-of-wordpress-language-locales/)

**Review by warengonzaga — APPROVED** [review]
LGTM! Thank you for the awesome contribution!

**Pull request merged**
